### ISSUE TITLE
Test-case related widget don't support test-related filters

### ISSUE THREAD

**Issue by rplevka** [reportportal/service-ui#1796]
I find it weird that the widgets don't support it.

E.g. I'd like to create a failure trend chart which would only show number of failed tests matching certain criteria, e.g.

(to get the trending chart of UI failures):
Failed test case trend where:  `launch-name == "foo" and testcase-name ~ "ui/"`

.. so far i can only apply launch metadata filter. I don't see any valid argument for such limitation.

**Comment by rplevka** [comment]
digging int othis some more I see one is aonly able to define filters for launches, but not for test cases.

**Comment by evjlobanova** [comment]
As a possible solution, you can try Component Health Check widget.

This widget shows the passing rate of the application components which are indicated by the specified attributes.

Use case:

Situation: As a Project Manager or Test Lead, a I want to see the most unstable place in my product ( application).

Solution: All test cases in my project in ReportPortal have an attributes. For example function: (order, team, configure, administrative), type: (backend, API, Unit, UI), ...., marketstate: (open, close), role: (ProjectManager, Member, Admin) and other. The attributes can be different and depending on your project needs.

A user can create a Component Health Check Widget and set attribute key = function for the 1st level, for the 2nd -type and for the 3rd - marketstate

So that a user will see on the first level several groups: order, team, configure, administrative. All groups will contain only test cases with an attribute that contain attribute key function. Each group has been grouped by attribute value: order, team, configure, administrative. If a user clicks on the group function: order, the system will show the second level of the widget. All test items on the second level will contain the attribute function: order and attributes which contain attribute key: type. And these items will be grouped by attribute values: backend, API, Unit, UI. The same logic will be applied for the next levels.
![image](https://user-images.githubusercontent.com/30413511/76970027-4b452b80-693c-11ea-8329-e9c0ee299b61.png)

https://reportportal.io/docs/Component-health-check

**Comment by evjlobanova** [comment]
We think about something like this:

![image](https://user-images.githubusercontent.com/30413511/78029327-0fad5700-7369-11ea-8327-a5d513e0402f.png)

You create a set of widgets and apply different filters and parameters on the fly.

**Comment by evjlobanova** [comment]
I have linked your request with the similar ones, and closed as a duplicate
